FROM node:lts-alpine as build

WORKDIR /app


COPY ./ProjetoCamaraDeputadosFrontEnd/package*.json ./


RUN npm install


COPY ./ProjetoCamaraDeputadosFrontEnd/ .


RUN npm run build

FROM nginx:alpine


COPY nginx/frontend.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]